Sunnysideup\Schedulizer\Model\ConfiguredSchedule:
  schedule_range_precedence:
    - Sunnysideup\Schedulizer\Model\ScheduleRange
    - Sunnysideup\Schedulizer\Model\ScheduleRange\ScheduleRangeDay
    - Sunnysideup\Schedulizer\Model\ScheduleRange\ScheduleRangeWeekDays
    - Sunnysideup\Schedulizer\Model\ScheduleRange\ScheduleRangeDayType
    - Sunnysideup\Schedulizer\Model\ScheduleRange\ScheduleRangeDefault
